# =====================================
# AIR CONFIG
# =====================================

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ./cmd/server"
bin = "tmp/main.exe"
full_bin = ""
delay = 1000
exclude_dir = ["tmp", "vendor"]
exclude_file = []
include_ext = ["go", "tpl", "tmpl", "html"]
stop_on_error = true
log = "air.log"

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[log]
time = true

[misc]
clean_on_exit = true
